query main {
  workouts {
    id
    name
    type
    zone
    description
    image {
      url
    }
  }
  days {
    id
    name
    cross {
      class {
        name
        type
        time
      }
      id
      hours
      minutes
    }
  }
  coaches {
    id
    name
    description
    fitness
    cross
    image {
      url
    }
    workouts {
      name
      zone
    }
  } 
}