query fitnessCoaches {
  background(id: "5de63fc875545300179a47d3") {
    id
    name
    image {
      url
    }
  }
  coaches {
    id
    name
    description
    fitness
    cross
    image {
      url
    }
    workouts {
      name
      zone
    }
  } 
}