query crossWorkoutsQuery {
  background(id: "5de6423f75545300179a47d8") {
    id
    name
    image {
      url
    }
  }
  days {
    id
    name
    cross {
      class {
        name
        type
        time
      }
      id
      hours
      minutes
    }
  }
  workouts {
    id
    name
    type
    zone
    description
    image {
      url
    }
  }
}