query kids {
  background(id: "5de642cc75545300179a47db") {
    id
    name
    image {
      url
    }
  } 
  days {
    id
    name
    cross {
      class {
        name
        type
        time
      }
      id
      hours
      minutes
    }
  }
  workouts {
    id
    name
    type
    zone
    description
    image {
      url
    }
  }
}