query personal {
  questions {
    id 
    question
    answer
  }
  coaches {
    id
    name
    description
    personal
    image {
      url
    }
    workouts {
      name
      zone
    }
  } 
}