query mainQuery {
  facilities {
    id 
    header
    subheader
    image {
      url
    }
  }
  zones {
    id
    name
    header
    subheader
    image {
      url
    }
  }
  memberships {
    id
    name
    price
    entries {
      entry
    }
  }
  background(id: "5de516ab30272e605c1903d1") {
    id
    name
    image {
      url
    }
  } 
  infos {
    id
    header
    subheader
    link
  }
}