query crossCoachesQuery {
  background(id: "5de6423f75545300179a47d8") {
    id
    name
    image {
      url
    }
  }
  coaches {
    id
    name
    description
    fitness
    cross
    personal
    image {
      url
    }
    workouts {
      name
      zone
    }
  } 
}